# Generated by Django 5.1.7 on 2025-03-20 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2024),
                            django.core.validators.MinValueValidator(1400),
                        ]
                    ),
                ),
                (
                    "raiting",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workers.worker"
                    ),
                ),
            ],
            options={
                "db_table": "school",
            },
        ),
    ]
