# Generated by Django 5.1.7 on 2025-03-20 13:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
            ],
            options={
                "db_table": "worker",
            },
        ),
    ]
