# Generated by Django 5.1.7 on 2025-03-20 13:33

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pupil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "_class",
                    models.ForeignKey(
                        db_column="class",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classes.class",
                    ),
                ),
            ],
            options={
                "db_table": "pupil",
            },
        ),
    ]
